services:
  db:
    image: postgres:16-alpine
    restart: always # Always restart if db crashes
    environment: # Env variables
      POSTGRES_DB: bitbox
      POSTGRES_USER: defaultbit
      POSTGRES_PASSWORD: password

  # Python backend service
  backend:
    build: ./audio-backend/ #path to backend docker file and application
    container_name: "python_backend"
    ports:
      - "5000:5000"
    environment: # Env variables
      DB_HOST: db
      DB_NAME: bitbox
      DB_USER: defaultbit # username for db
      DB_PASSWORD: password # Password for db
      DB_PORT: 5432
      DB_SETUP_STAT: 0
    depends_on:
      - db
  
  # React native front end serverice
  frontend:
    build: ./bitbox/ # Path to front end dockerfile
    container_name: "react_frontend"
    ports:
      - "8081:8081"
    depends_on:
      - backend
