FROM python:3.9.22-alpine3.22

# Base directory in the docker container
WORKDIR /audio-backend

# Copy all files to /app on container
COPY . /audio-backend/

EXPOSE 8000

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app/main.py"]