FROM python:3.13-slim

# Base directory in the docker container
WORKDIR /audio-backend

# Ensures print() statements show up immediately
ENV PYTHONUNBUFFERED=1

# Enables Flask debug features (optional, for development only)
ENV FLASK_ENV=development
ENV FLASK_APP=app.py

# Install system dependencies
#RUN apt-get update && apt-get install -y --no-install-recommends \
    #build-essential \
    #libsndfile1 \
    #ffmpeg \
    #&& rm -rf /var/lib/apt/lists/*

# Copy all files to /app on container
COPY . /audio-backend/

EXPOSE 8000

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-u", "app/main.py"]